parameters:
    sidus_data_class: ClientNamespace\EAVModelBundle\Entity\Data
    sidus_value_class: ClientNamespace\EAVModelBundle\Entity\Value

sidus_eav_model:
    data_class: '%sidus_data_class%'
    value_class: '%sidus_value_class%'
    serializer_enabled: true

clever_age_eav_manager_user:
    mailer:
        company: Client Company
        from_email: no-reply@client-company.com
        from_name: Client

imports:
    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }
    - { resource: admin.yml }
    - { resource: eav_datagrid.yml }

    # Model configuration, order of files matters
    - { resource: project/base.yml }
    - { resource: project/page.yml }
    - { resource: project/user.yml }
