version: '2'

services:
    www:
        build: www
        working_dir: /var/www/current
        depends_on:
            - mysql
            - mailcatcher
            - rabbitmq
        ports:
            - ${WWW_PORT}:80
        volumes:
            - ${APP_DIR}:/var/www/current
            - ./www/nginx/sites-available/:/etc/nginx/sites-available/
            - ./www/supervisor/:/etc/supervisor/conf.d/
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SF_DATABASE_HOST: mysql
            SF_DATABASE_PORT: 3306
            SF_DATABASE_NAME: ${MYSQL_DATABASE}
            SF_DATABASE_USER: ${MYSQL_USER}
            SF_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            SF_MAILER_TRANSPORT: smtp
            SF_MAILER_HOST: mailcatcher:1025
            SF_MAILER_USER: '~'
            SF_MAILER_PASSWORD: '~'
            SF_SECRET: ${SF_SECRET}
            SF_RABBITMQ_HOST: rabbitmq
            SF_RABBITMQ_PORT: 5672
            SF_RABBITMQ_USER: rb_user
            SF_RABBITMQ_PASS: rb_passwd
            SF_ELASTIC_SEARCH_HOST: elasticsearch
            SF_ELASTIC_SEARCH_PORT: 9200
            SF_ELASTIC_SEARCH_PASSWORD: elasticsearch
            SF_TRUSTED_PROXIES: '~'

    mysql:
        image: mariadb
        ports:
            - ${DB_PORT}:3306
        volumes:
            - volume_mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - ${MAILCATCHER_PORT}:1080

    deploy:
        build: capistrano
        command: /bin/true
        volumes:
            - ${APP_DIR}/deploy:/source
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SSH_AUTH_SOCK: '/ssh-agent'

    elasticsearch:
        image:  docker.elastic.co/elasticsearch/elasticsearch:6.5.0
        environment:
            discovery.type: single-node
            ELASTIC_PASSWORD: elasticsearch
        volumes:
            - volume_elasticsearch:/usr/share/elasticsearch/data

    rabbitmq:
        image: rabbitmq:3.7-management
        environment:
            RABBITMQ_DEFAULT_USER: rb_user
            RABBITMQ_DEFAULT_PASS: rb_passwd
        ports:
            - 15672:15672
        volumes:
            - volume_rabbitmq:/var/lib/rabbitmq

volumes:
    volume_rabbitmq:
        driver: local
    volume_mysql:
        driver: local
    volume_elasticsearch:
        driver: local
